/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'li-blue': '#0A66C2',
        'li-blue-dark': '#004182',
        'li-blue-light': '#378FE9',
        'li-bg-primary': '#FFFFFF',
        'li-bg-secondary': '#F3F2EF',
        'li-bg-tertiary': '#EDF3F8',
        'li-bg-hover': '#EDF3F8',
        'li-bg-selected': '#EDF3F8',
        'li-text-primary': 'rgba(0, 0, 0, 0.9)',
        'li-text-secondary': 'rgba(0, 0, 0, 0.75)',
        'li-text-tertiary': 'rgba(0, 0, 0, 0.6)',
        'li-text-disabled': 'rgba(0, 0, 0, 0.3)',
        'li-border-subtle': 'rgba(140, 140, 140, 0.2)',
        'li-border-standard': 'rgba(0, 0, 0, 0.08)',
        'li-border-emphasis': 'rgba(0, 0, 0, 0.3)',
        'li-tag-bg': 'rgba(0, 0, 0, 0.08)',
        'li-tag-beta': '#DDE7F1',
        'li-tag-crm': '#EDF3F8',
        'li-success': '#2F7B15',
        'li-success-bg': '#EDF3F8',
      },
      fontFamily: {
        display: [
          'Community',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
        body: [
          'Community',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
        nav: [
          'Community',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
        brand: [
          'Community Pro',
          'Community',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
      },
      fontSize: {
        'ds-display': ['24px', { lineHeight: '1.25', letterSpacing: '0.36px' }],
        'ds-heading': ['20px', { lineHeight: '1.25', letterSpacing: '0.38px' }],
        'ds-large': ['16px', { lineHeight: '1.25', letterSpacing: '-0.32px' }],
        'ds-base': ['14px', { lineHeight: '1.25', letterSpacing: '-0.15px' }],
        'ds-small': ['12px', { lineHeight: '1.25', letterSpacing: '-0.15px' }],
      },
      spacing: {
        'ds-2': '2px',
        'ds-4': '4px',
        'ds-8': '8px',
        'ds-12': '12px',
        'ds-16': '16px',
        'ds-24': '24px',
        'ds-32': '32px',
        'ds-48': '48px',
      },
      borderRadius: {
        'ds-button': '16px',
        'ds-card': '8px',
        'ds-tag': '4px',
        'ds-circle': '1000px',
        'ds-spotlight': '100px',
      },
    },
  },
  plugins: [],
};
